openapi: 3.0.1
tags:
  - name: Transmission
    description: Data relating to the infrastructure on and management of the transmission network
    externalDocs:
      url: https://www.bmreports.com/bmrs/?q=transmission/
  - name: Demand
    description: Data relating to forecasts, out-turn, and reductions in demand
    externalDocs:
      url: https://www.bmreports.com/bmrs/?q=demand/
  - name: Generation
    description: Data relating to forecasts, out-turn, and reductions in generation 
    externalDocs:
      url: https://www.bmreports.com/bmrs/?q=generation/
  - name: Balancing
    description: Data relating to the prices, volumes, and units operating in short-term power markets
    externalDocs:
      url: hhttps://www.bmreports.com/bmrs/?q=balancing/
info:
  title: "{{ API_spec['title'] }}"
  description: "{{ API_spec['description'] }}"
  version: "2.0"
servers:
  - url: "{{ API_spec['root_url'] }}"
paths:{% for stream in API_spec['streams'] %}
  {{ stream['endpoint'] }}:
    get:{% if 'x-title' in stream %}
      x-title: "{{ stream['x-title'] }}"{% endif %}
      description: "{{ stream['description'] }}"{% if 'tags' in stream %}
      tags:{% for tag in stream['tags'] %}
        - {{ tag }}{% endfor %}{% endif %}
      parameters:{% for parameter in stream['parameters'] %}
        - name: "{{ parameter['name'] }}"
          in: "query"
          schema:
            type: "{{ parameter['type'] }}"{% if 'example' in parameter %}
          example: "{{ parameter['example'] }}"{% elif 'examples' in parameter %}
          examples:{% for example in parameter['examples'] %}
            {{ example }}:
              value: "{{ example }}"{% endfor %}{% endif %}{% endfor %}
      responses:
        '200':
          description: "{{ stream['description'] }}"
      servers:
        - url: "{{ API_spec['root_url'] }}"
    servers:
      - url: "{{ API_spec['root_url'] }}"
    {% endfor %}